//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIQuanLyDatVe.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietVe
    {
        public string idchitietve { get; set; }
        public string idve { get; set; }
        public Nullable<int> soghengoi { get; set; }
    
        public virtual Ve Ve { get; set; }
    }
}
