//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIQuanLyDatVe.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuyenXe
    {
        public string machuyenxe { get; set; }
        public string maxe { get; set; }
        public string malotrinh { get; set; }
        public Nullable<System.DateTime> thoigian { get; set; }
        public string makip { get; set; }
        public string mataixe { get; set; }
        public string maphuxe { get; set; }
    
        public virtual Kip Kip { get; set; }
        public virtual LoTrinh LoTrinh { get; set; }
        public virtual Xe Xe { get; set; }
    }
}
