//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIQuanLyDatVe.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiemDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DiemDon()
        {
            this.Ves = new HashSet<Ve>();
        }
    
        public string madiemdon { get; set; }
        public string madiemtrungchuyen { get; set; }
        public string tendiemdon { get; set; }
    
        public virtual DiemTrungChuyen DiemTrungChuyen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ve> Ves { get; set; }
    }
}
