//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIQuanLyDatVe.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lich
    {
        public string malich { get; set; }
        public string makip { get; set; }
        public Nullable<int> sochuyen { get; set; }
        public string malotrinh { get; set; }
    
        public virtual Kip Kip { get; set; }
        public virtual LoTrinh LoTrinh { get; set; }
    }
}
