//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIQuanLyDatVe.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ve
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ve()
        {
            this.ChiTietVes = new HashSet<ChiTietVe>();
        }
    
        public string mave { get; set; }
        public string makhachhang { get; set; }
        public string machitietlotrinh { get; set; }
        public string madiemdon { get; set; }
        public string madiemxuong { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<int> tongtien { get; set; }
        public string ghichu { get; set; }
        public string matrangthaivexe { get; set; }
        public string manhanvien { get; set; }
    
        public virtual ChiTietLoTrinh ChiTietLoTrinh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietVe> ChiTietVes { get; set; }
        public virtual DiemDon DiemDon { get; set; }
        public virtual DiemXuong DiemXuong { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual TrangThaiVeXe TrangThaiVeXe { get; set; }
    }
}
